# Generated by Django 5.0.3 on 2024-03-22 17:54

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_inactive',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True, validators=[account.validation.validate_email]),
            preserve_default=False,
        ),
    ]
