# Generated by Django 5.0.3 on 2024-03-23 07:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_title', models.TextField(max_length=300)),
                ('cat', models.CharField(choices=[('Electronics', 'Electronics'), ('Vegetables', 'Vegetables'), ("Women's Clothes", "Women's Clothes"), ('Mens Clothes', 'Mens Clothes'), ('Teddy', 'Teddy')], max_length=20)),
                ('quantity_type', models.CharField(choices=[('/Piece', '/Piece'), ('/Kg', '/Kg'), ('/Packet', '/Packet')], max_length=20)),
                ('prize', models.BigIntegerField(max_length=5)),
                ('offer', models.IntegerField(max_length=3)),
                ('image', models.ImageField(max_length=500, upload_to='images')),
                ('total', models.IntegerField(max_length=5)),
                ('available', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('road', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin', models.IntegerField(blank=True, default=None, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=5)),
                ('prize', models.IntegerField(max_length=5)),
                ('total_prize', models.FloatField(max_length=10)),
                ('order_date', models.DateField(default=datetime.date(2024, 3, 23))),
                ('order_time', models.TimeField(default=datetime.datetime(2024, 3, 23, 13, 20, 42, 402408))),
                ('status', models.BooleanField(default=False)),
                ('order_address', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.product')),
            ],
        ),
    ]
