# Generated by Django 5.0.3 on 2024-03-23 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_order_order_time_alter_order_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 23, 8, 6, 57, 777665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.BigIntegerField(),
        ),
    ]
