# Generated by Django 5.0.3 on 2024-03-23 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_order_order_time_alter_orderaddress_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
