# Generated by Django 5.0.3 on 2024-03-23 09:52

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('/peace', '/Peace'), ('/kg', '/Kg'), ('/packet', '/Packet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[account.validation.validate_email]),
        ),
    ]
