# Generated by Django 5.0.3 on 2024-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_dob_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
