# Generated by Django 5.0.3 on 2024-03-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
    ]
